### ISSUE TITLE
"From" address not respected when custom values sent to wp_mail()

### ISSUE THREAD

**Issue by wpnzach** [mailgun/wordpress-plugin#43]
It seems in the current plugin iteration that MailGun only sends from the "From" address specified in the MailGun settings, or, if not set, from the WordPress admin email address.

When we try to send emails from another "From" address, it is overwritten by the plugin before being sent which is causing problems for us and for our users (we are the authors of the Ninja Forms plugin here: https://github.com/wpninjas/ninja-forms/)

**Comment by pirogoeth** [comment]
Hey @wpnzach, which version(s) of our plugin are you getting reports for? I have added a fix for this in one of the previous releases.

**Comment by wpnzach** [comment]
Is it possible to get this option ENABLED by default?  Making a change like that broke a lot of sites, including ours and our users.  Awesome to see that option is there now so we can assist moving forward, but we're looking to slow down the innundation of support requests from users who think we broke their emails.

**Comment by pirogoeth** [comment]
@wpnzach Get "override from details" enabled by default? I had complaints about it being enabled by default on the support forums since it was overriding the values passed to `wp_main` by other plugins. Any chance I could get you in our [Gitter channel](https://gitter.im/mailgun/wordpress-plugin) so we can talk about this easier?
