### ISSUE TITLE
SMTP Security

### ISSUE THREAD

**Issue by rbaugh** [mailgun/wordpress-plugin#60]
Noticed that for SMTP, the SMTPSecure property that is used when choosing the secure option is SSL instead of tls and the port is 465 instead of 587. This seems to be older security standards for SMTPS. Why are you using older standards for SMTPS?

Also, wouldn't it be better to use the domain as the host so that the EHLO matches up with the account on MailGun and not the actual domain the site is running on?

https://github.com/mailgun/wordpress-plugin/blob/master/mailgun.php#L121

**Comment by pirogoeth** [comment]
Hello @rbaugh, I will switch PHPMailer to use TLS if available. As far as our SMTP port configurations go, 465 enforces TLS/SSL usage, but 587 and 25 can be used as plaintext/insecure with support for STARTTLS, which is why turning off secure SMTP switches to port 587. 

With regard to sending domain as host for EHLO -- according to RFC, the address provided by HELO/EHLO should be the domain of the SMTP client, and I don't really see a reason to make a change to the default behaviour.

**Comment by rbaugh** [comment]
TLS is only available on port 587 in regards to MailGun. At least when I
was trying command line it wasn't responding to starttls on port 465.

-- 
Richard Baugh

**Comment by pirogoeth** [comment]
@rbaugh Port 465 only allows connections that immediately negotiate SSL/TLS (ie., `openssl s_client -host smtp.mailgun.org -port 465` will connect and the server will begin to negotiate SMTP protocol *but* `telnet smtp.mailgun.org 465` will not because it does not negotiate SSL/TLS).

----

Both ports 25 and 587 initially accept plain connections but will negotiate TLS during the beginning of SMTP negotiation:
```
λ telnet smtp.mailgun.org 25
Trying 34.206.32.229...
Connected to smtp.mailgun.org.
Escape character is '^]'.
220 ak47 ESMTP ready
EHLO client
250-ak47
250-AUTH PLAIN LOGIN
250-SIZE 52428800
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-SMTPUTF8
250 STARTTLS
STARTTLS
220 2.0.0 Start TLS
```

And the same thing happens with 587. You can also have OpenSSL connect and immediately perform STARTTLS negotiation after connecting with `openssl s_client -host smtp.mailgun.org -port 587 -starttls smtp`. Same thing works with port 25.

**Comment by pirogoeth** [comment]
@rbaugh Just checked release 1.5.8.5 in to Wordpress SVN today. Should be available shortly.
