### ISSUE TITLE
Multisite with multiple custom domain

### ISSUE THREAD

**Issue by abdusfauzi** [mailgun/wordpress-plugin#86]
If using multisite force me to use the constant in `wp-config.php`, how about sites that are using custom domain instead of the subdomain? Can we set its own config, thru option page?

**Comment by uavn** [comment]
Due to the changelog is was already done.

= 1.7.1 (2019-02-07): =- Reinstall settings page for multisites.

I checked - and I was able to configure two different sites of multisite setup with different credentials:

![Screenshot from 2020-09-22 22-05-23](https://user-images.githubusercontent.com/315338/94288858-9631a280-ff60-11ea-9622-7a8dbff3224d.png)
